<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="SignUp"
           tests="11"
           failures="2"
           errors="0"
           skipped="6"
           time="40.745">
  <properties />
            <testcase name="thirdTestCase" time="3.203" classname="TracksPageScripts.Linkedin_SignUp_PageScripts">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	expected [Please enter your email address] but found [Please enter your email address or mobile number]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Please enter your email address] but found [Please enter your email address or mobile number]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
  TracksPageScripts.Linkedin_SignUp_PageScripts.thirdTestCase(Linkedin_SignUp_PageScripts.java:120)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
  org.testng.internal.Invoker.retryFailed(Invoker.java:967)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1146)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:782)
  org.testng.TestRunner.run(TestRunner.java:632)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
  org.testng.SuiteRunner.run(SuiteRunner.java:268)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
  org.testng.TestNG.run(TestNG.java:1064)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
            <testcase name="fifthTestCase" time="3.338" classname="TracksPageScripts.Linkedin_SignUp_PageScripts">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	expected [Please enter a valid email address] but found [Please enter a valid email address or mobile number]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Please enter a valid email address] but found [Please enter a valid email address or mobile number]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
  TracksPageScripts.Linkedin_SignUp_PageScripts.fifthTestCase(Linkedin_SignUp_PageScripts.java:170)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
  org.testng.internal.Invoker.retryFailed(Invoker.java:967)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1146)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:782)
  org.testng.TestRunner.run(TestRunner.java:632)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
  org.testng.SuiteRunner.run(SuiteRunner.java:268)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
  org.testng.TestNG.run(TestNG.java:1064)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
            <testcase name="thirdTestCase" time="0.0" classname="TracksPageScripts.Linkedin_SignUp_PageScripts">
          <skipped />
    </testcase>
            <testcase name="fifthTestCase" time="0.0" classname="TracksPageScripts.Linkedin_SignUp_PageScripts">
          <skipped />
    </testcase>
            <testcase name="thirdTestCase" time="0.0" classname="TracksPageScripts.Linkedin_SignUp_PageScripts">
          <skipped />
    </testcase>
            <testcase name="fifthTestCase" time="0.0" classname="TracksPageScripts.Linkedin_SignUp_PageScripts">
          <skipped />
    </testcase>
            <testcase name="fifthTestCase" time="0.0" classname="TracksPageScripts.Linkedin_SignUp_PageScripts">
          <skipped />
    </testcase>
            <testcase name="thirdTestCase" time="0.0" classname="TracksPageScripts.Linkedin_SignUp_PageScripts">
          <skipped />
    </testcase>
  
            <testcase name="fourthTestCase" time="3.756" classname="TracksPageScripts.Linkedin_SignUp_PageScripts" />
                <testcase name="secondTestCase" time="3.399" classname="TracksPageScripts.Linkedin_SignUp_PageScripts" />
                <testcase name="firstTestCase" time="6.843" classname="TracksPageScripts.Linkedin_SignUp_PageScripts" />
      
</testsuite>
